name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Buildx
        id: buildx
        uses: docker/build-push-action@v2
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: adrielporto/codelandia:latest

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [ continuous-integration ]
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-3-86-163-207.compute-1.amazonaws.com"
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_RSA }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker rm -f codelandia
            sudo docker pull adrielporto/codelandia:latest
            sudo docker run -d --name=codelandia --network host -p 5173:5173 adrielporto/codelandia npm run dev
